export const environment = {
  production: false,
  prices: 'https://supernode.saiive.live/api/v1/mainnet/DFI/coin-price/USD',
  oraclePrices: 'https://ocean.defichain.com/v0/mainnet/prices?size=1000',
  listpoolpairs: 'https://supernode.saiive.live/api/v1/mainnet/DFI/listpoolpairs?size=200',
  poolpairsocean: 'https://ocean.defichain.com/v0/mainnet/poolpairs?size=200',
  health: 'https://supernode.saiive.live/api/v1/health',
  cur: 'https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/usd.json',
  cake: 'https://api.cakedefi.com/coins/apy',
  dfx: 'https://api.dfx.swiss/v1/statistic',
  oceanstats: 'https://ocean.defichain.com/v0/mainnet/stats',
  blocks: 'https://ocean.defichain.com/v0/mainnet/blocks?size=2000',
  supernode_account: 'https://supernode.saiive.live/api/v1/mainnet/DFI/account/',
  address_vaults: 'https://ocean.defichain.com/v0/mainnet/address/ADDRESS_VAULTS/vaults',
  mamon_account: 'https://sync.defichain-masternode-monitor.com/v1/KEY/masternodes',
  mamon_account_node: 'https://api.defichain-masternode-monitor.com/v1/masternodes/info/',
  burninfo: 'https://api.mydeficha.in/v1/getburninfo/',
  version: '8.16.4',
  bittrex: 'https://api.bittrex.com/v3/currencies/DFI',
  kucoin: 'https://api.kucoin.com/api/v1/currencies/DFI',
  graphql: 'https://next.graphql.defichain-income.com/graphql',
  // Matomo
  matomoId: 6,
  matomoUrl: 'https://analytics.topiet.de/'
};
